import type { Metadata } from "next";
import BlogNav from "@/components/blog/BlogNav";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
<BlogNav/>
{children}
    </>
  );
}
